// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getVolume: (id: Identifier) => typedError<number | null, string>(__TAURI_INVOKE("get_volume", { id })),
	setVolume: (id: Identifier, volume: number | null) => typedError<null, string>(__TAURI_INVOKE("set_volume", { id, volume })),
	setMute: (id: Identifier) => typedError<null, string>(__TAURI_INVOKE("set_mute", { id })),
	setUnmute: (id: Identifier) => typedError<null, string>(__TAURI_INVOKE("set_unmute", { id })),
	getIcon: (id: Identifier) => typedError<number[], string>(__TAURI_INVOKE("get_icon", { id })),
	getApplication: (id: number) => typedError<AudioApplication, string>(__TAURI_INVOKE("get_application", { id })),
	getPlaybackDevices: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_playback_devices")),
	getDeviceApplications: (id: string) => typedError<number[], string>(__TAURI_INVOKE("get_device_applications", { id })),
	discoverServerAddress: () => __TAURI_INVOKE<string | null>("discover_server_address"),
};

/* Constants */
export const UPDATE_EVENT_NAME = "update_event" as const;

export const VOLUME_LABEL_EVENT = "volume-control-panel" as const;

export const WEBSOCKET_PORT = 9002 as const;

/* Types */
export type AudioApplication = {
	process: ProcessInfo,
	session_type: SessionType,
	direction: SessionDirection,
	volume: AudioVolume,
	device_id: string,
};

export type AudioDevice = {
	id: string,
	name: string,
	friendly_name: string,
	direction: SessionDirection,
	is_default: boolean,
	volume: AudioVolume,
};

export type AudioVolume = {
	current: number | null,
	muted: boolean,
};

export type ChangeType = { kind: "audioVolume"; volume: number | null; mute: boolean } | { kind: "iconPathChange"; path: string } | { kind: "stateChange"; state: EntityState } | { kind: "nameChange"; name: string };

export type Command = { type: "get_volume"; data: {
	id: Identifier,
} } | { type: "set_volume"; data: {
	id: Identifier,
	volume: number | null,
} } | { type: "set_mute"; data: {
	id: Identifier,
	mute: boolean,
} } | { type: "get_applications"; data: {
	id: string,
} } | { type: "get_application"; data: {
	id: number,
} } | { type: "get_icon"; data: {
	id: Identifier,
} } | { type: "get_playback_devices" };

export type CommandRequest = {
	id: number,
	command: Command,
};

export type CommandResponse = {
	type: "CommandResponse",
	id: number,
	response: Response,
};

export type EntityState = "disconnect" | "created";

export type Identifier = { type: "app"; content: number } | { type: "device"; content: string };

export type ProcessInfo = {
	id: number,
	name: string,
	path: string | null,
};

export type Response = { type: "volume"; data: {
	id: Identifier,
	volume: AudioVolume,
} } | { type: "application_list"; data: {
	id: string,
	apps: number[],
} } | { type: "application"; data: AudioApplication } | { type: "icon"; data: {
	id: number,
	data: number[],
} } | { type: "device_list"; data: AudioDevice[] } | { type: "error"; data: {
	message: string,
} } | { type: "a_c_k" };

export type SessionDirection = "Render" | "Capture" | "Unknown";

export type SessionType = "Application" | "Device" | "System" | "Unknown";

export type UpdateChange = {
	id: Identifier,
	change: ChangeType,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

