// This file has been generated by Tauri Specta. Do not edit this file manually.


/* Types */
export type AudioApplication = {
	process: ProcessInfo,
	session_type: SessionType,
	direction: SessionDirection,
	volume: AudioVolume,
	device_id: string,
};

export type AudioDevice = {
	id: string,
	name: string,
	friendly_name: string,
	direction: SessionDirection,
	is_default: boolean,
	volume: AudioVolume,
};

export type AudioVolume = {
	current: number | null,
	muted: boolean,
};

export type ChangeType = { kind: "audioVolume"; volume: number | null; mute: boolean } | { kind: "iconPathChange"; path: string } | { kind: "stateChange"; state: EntityState } | { kind: "nameChange"; name: string };

export type Command = { type: "get_volume"; data: {
	id: Identifier,
} } | { type: "set_volume"; data: {
	id: Identifier,
	volume: number | null,
} } | { type: "set_mute"; data: {
	id: Identifier,
	mute: boolean,
} } | { type: "get_applications"; data: {
	id: string,
} } | { type: "get_application"; data: {
	id: number,
} } | { type: "get_icon"; data: {
	id: number,
} } | { type: "get_playback_devices" };

export type CommandRequest = {
	id: number,
	command: Command,
};

export type CommandResponse = {
	type: "CommandResponse",
	id: number,
	response: Response,
};

export type EntityState = "disconnect" | "created";

export type Identifier = { type: "app"; content: number } | { type: "device"; content: string };

export type ProcessInfo = {
	id: number,
	name: string,
	path: string | null,
};

export type Response = { type: "volume"; data: {
	id: Identifier,
	volume: AudioVolume,
} } | { type: "application_list"; data: {
	id: string,
	apps: number[],
} } | { type: "application"; data: AudioApplication } | { type: "icon"; data: {
	id: number,
	data: number[],
} } | { type: "device_list"; data: AudioDevice[] } | { type: "error"; data: {
	message: string,
} } | { type: "a_c_k" };

export type SessionDirection = "Render" | "Capture" | "Unknown";

export type SessionType = "Application" | "Device" | "System" | "Unknown";

export type UpdateChange = {
	id: Identifier,
	change: ChangeType,
};

