[package]
name = "helper-win32"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "firewall_helper"
path = "src/main.rs"

[build-dependencies]
winresource = { version = "0.1.31", features = [] }

[target.'cfg(windows)'.dependencies]
windows_firewall = { version = "0.7.0" }
windows = { version = "0.62.2", features = [
    # Local time
    "Win32_System_Time",
] }
